### ISSUE TITLE
Fails to build on 3.12

### ISSUE THREAD

**Issue by wRAR** [MagicStack/uvloop#531]
Just for your information, I've tried to install uvloop on 3.12.0-alpha.5 and it fails with "error: ‘PyLongObject’ {aka ‘struct _longobject’} has no member named ‘ob_digit’" (in many places).

**Comment by wRAR** [comment]
I see it's reported upstream at https://github.com/cython/cython/issues/5238
