### ISSUE TITLE
Fails to build on PyPy 3.11

### ISSUE THREAD

**Issue by wRAR** [MagicStack/uvloop#657]
```      
uvloop/loop.c: At top level:
uvloop/loop.c:211059:12: fatal error: internal/pycore_frame.h: No such file or directory
211059 |   #include "internal/pycore_frame.h"
       |            ^~~~~~~~~~~~~~~~~~~~~~~~~
```

lxml has [the same problem](https://bugs.launchpad.net/lxml/+bug/2098055) so I guess it's the same underlying issue that requires regenerating C code with Cython 3.0.12.

**Comment by lucascompython** [comment]
This means it used to work with PyPy 3.10? 
I never got it working.

**Comment by wRAR** [comment]
`-Werror=implicit-function-declaration` is not enabled by default on Ubuntu 24.04 used in our GitHub CI jobs but is enabled on your system. The underlying issue seems to be #537

**Comment by lucascompython** [comment]
Yeah, #537 seems to be the issue, but you did have it working on PyPy3.10 right?
I get that error on PyPy3.10, PyPy3.11, PyPy3.11 compiled from source using Cython 3.0 and Cython 3.1.0 alpha 1.

**Comment by wRAR** [comment]
Again, it builds fine on the GitHub CI `ubuntu-24.04` runner env and that's why it works there, so I can only assume that the GCC used on that runner (be it the default Ubuntu one or some provided by the runner image) doesn't have `-Werror=implicit-function-declaration` enabled by default, unlike e.g. current Debian unstable.

**Comment by lucascompython** [comment]
I get that, I can't turn off those warning, and it builds, and I can install uvloop, but then it doesn't run.
Because, well, those symbols aren't defined anywhere.

```
Traceback (most recent call last):
  File "/home/lucas/Desktop/tests/uvloop_pypy/main.py", line 4, in <module>
    import uvloop
  File "/home/lucas/Desktop/tests/uvloop/uvloop/__init__.py", line 9, in <module>
    from .loop import Loop as __BaseLoop  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: /home/lucas/Desktop/tests/uvloop/uvloop/loop.pypy310-pp73-x86_64-linux-gnu.so: undefined symbol: PyContext_CopyCurrent
```

**Comment by wRAR** [comment]
That's also old and not specific to PyPy 3.10: #370 

(note that I have no idea about any of this, but it's easily googleable)

**Comment by lucascompython** [comment]
You probably mean #380.
But yeah, I'm just wondering how it works on CI and I can't seem to get it working.

**Comment by fantix** [comment]
It might be that the recent updates in the toolchain somehow got it working, but I think that's unlikely and quite unexpected, as uvloop does not support PyPy at this moment. Please also see Yury's comments on porting uvloop to PyPy in #82.
