### ISSUE TITLE
Don't compile uvloop 0.13 on mips.

### ISSUE THREAD

**Issue by Kirya2k** [MagicStack/uvloop#264]
Don't compile version 0.13.
Version 0.12.2 compile before normally.
Where to find the reason ?

>>> import sys
>>> print(sys.version)
3.7.2 (default, May 25 2019, 13:27:38)
[GCC 7.4.0]
>>>
~/uvloop-0.13 # uname -a
Linux Keenetic_Giga 3.4.113 #1 SMP Mon Jun 17 21:01:32 MSK 2019 mips GNU/Linux
( This is https://github.com/Entware/Entware/)

 copying uvloop/includes/python.pxd -> build/lib.linux-mips-3.7/uvloop/includes
  copying uvloop/includes/stdlib.pxi -> build/lib.linux-mips-3.7/uvloop/includes
  copying uvloop/includes/system.pxd -> build/lib.linux-mips-3.7/uvloop/includes
  copying uvloop/includes/uv.pxd -> build/lib.linux-mips-3.7/uvloop/includes
  warning: build_py: byte-compiling is disabled, skipping.

  running build_ext
  checking for a BSD-compatible install... ./install-sh -c
  checking whether build environment is sane... yes
  checking for a thread-safe mkdir -p... /opt/bin/mkdir -p
  checking for gawk... no
  checking for mawk... no
  checking for nawk... no
  checking for awk... awk
  checking whether make sets $(MAKE)... yes
  checking whether make supports nested variables... yes
  checking build system type... mipsel-unknown-linux-gnu
  checking host system type... mipsel-unknown-linux-gnu
  checking for gcc... gcc
  checking whether the C compiler works... yes
  checking for C compiler default output file name... a.out
  checking for suffix of executables...
  checking whether we are cross compiling... no
  checking for suffix of object files... o
  checking whether we are using the GNU C compiler... yes
  checking whether gcc accepts -g... yes
  checking for gcc option to accept ISO C89... none needed
  checking whether gcc understands -c and -o together... yes
  checking for style of include used by make... GNU
  checking dependency style of gcc... gcc3
  checking if gcc supports -pedantic flag... yes
  checking for gcc way to treat warnings as errors... -Werror
  checking if gcc supports -fvisibility=hidden... yes
  checking if gcc supports -g flag... yes
  checking if gcc supports -std=gnu89 flag... yes
  checking if gcc supports -Wall flag... yes
  checking if gcc supports -Wextra flag... yes
  checking if gcc supports -Wno-unused-parameter flag... yes
  checking if gcc supports -Wstrict-prototypes flag... yes
  checking for ar... ar
  checking the archiver (ar) interface... ar
  checking how to print strings... printf
  checking for a sed that does not truncate output... /opt/bin/sed
  checking for grep that handles long lines and -e... /opt/bin/grep
  checking for egrep... /opt/bin/grep -E
  checking for fgrep... /opt/bin/grep -F
  checking for ld used by gcc... /opt/bin/ld
  checking if the linker (/opt/bin/ld) is GNU ld... yes
  checking for BSD- or MS-compatible name lister (nm)... /opt/bin/nm -B
  checking the name lister (/opt/bin/nm -B) interface... BSD nm
  checking whether ln -s works... yes
  checking the maximum length of command line arguments... 32768
  checking whether the shell understands some XSI constructs... yes
  checking whether the shell understands "+="... no
  checking how to convert mipsel-unknown-linux-gnu file names to mipsel-unknown-linux-gnu format... func_convert_file_noop
  checking how to convert mipsel-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
  checking for /opt/bin/ld option to reload object files... -r
  checking for objdump... objdump
  checking how to recognize dependent libraries... pass_all
  checking for dlltool... no
  checking how to associate runtime and link libraries... printf %s\n
  checking for archiver @FILE support... @
  checking for strip... strip
  checking for ranlib... ranlib
  checking command to parse /opt/bin/nm -B output from gcc object... ok
  checking for sysroot... no
  checking for mt... no
  checking if : is a manifest tool... no
  checking how to run the C preprocessor... gcc -E
  checking for ANSI C header files... yes
  checking for sys/types.h... yes
  checking for sys/stat.h... yes
  checking for stdlib.h... yes
  checking for string.h... yes
  checking for memory.h... yes
  checking for strings.h... yes
  checking for inttypes.h... yes
  checking for stdint.h... yes
  checking for unistd.h... yes
  checking for dlfcn.h... yes
  checking for objdir... .libs
  checking if gcc supports -fno-rtti -fno-exceptions... no
  checking for gcc option to produce PIC... -fPIC -DPIC
  checking if gcc PIC flag -fPIC -DPIC works... yes
  checking if gcc static flag -static works... no
  checking if gcc supports -c -o file.o... yes
  checking if gcc supports -c -o file.o... (cached) yes
  checking whether the gcc linker (/opt/bin/ld) supports shared libraries... yes
  checking whether -lc should be explicitly linked in... no
  checking dynamic linker characteristics... GNU/Linux ld.so
  checking how to hardcode library paths into programs... immediate
  checking whether stripping libraries is possible... yes
  checking if libtool supports shared libraries... yes
  checking whether to build shared libraries... yes
  checking whether to build static libraries... yes
  checking whether make supports nested variables... (cached) yes
  checking for dlopen in -ldl... yes
  checking for kstat_lookup in -lkstat... no
  checking for gethostbyname in -lnsl... yes
  checking for perfstat_cpu in -lperfstat... no
  checking for pthread_mutex_init in -lpthread... yes
  checking for clock_gettime in -lrt... yes
  checking for sendfile in -lsendfile... no
  checking for socket in -lsocket... no
  checking for special C compiler options needed for large files... no
  checking for _FILE_OFFSET_BITS value needed for large files... 64
  checking sys/ahafs_evProds.h usability... no
  checking sys/ahafs_evProds.h presence... no
  checking for sys/ahafs_evProds.h... no
  checking that generated files are newer than configure... done
  configure: creating ./config.status
  config.status: creating Makefile
  config.status: creating libuv.pc
  config.status: executing depfiles commands
  config.status: executing libtool commands
    CC       src/libuv_la-fs-poll.lo
    CC       src/libuv_la-inet.lo
    CC       src/libuv_la-strscpy.lo
    CC       src/libuv_la-idna.lo
    CC       src/libuv_la-threadpool.lo
    CC       src/libuv_la-timer.lo
    CC       src/libuv_la-uv-data-getter-setters.lo
    CC       src/libuv_la-uv-common.lo
    CC       src/libuv_la-version.lo
    CC       src/unix/libuv_la-async.lo
    CC       src/unix/libuv_la-core.lo
    CC       src/unix/libuv_la-dl.lo
    CC       src/unix/libuv_la-fs.lo
    CC       src/unix/libuv_la-getaddrinfo.lo
    CC       src/unix/libuv_la-getnameinfo.lo
    CC       src/unix/libuv_la-loop-watcher.lo
    CC       src/unix/libuv_la-loop.lo
    CC       src/unix/libuv_la-pipe.lo
    CC       src/unix/libuv_la-poll.lo
    CC       src/unix/libuv_la-process.lo
    CC       src/unix/libuv_la-signal.lo
    CC       src/unix/libuv_la-stream.lo
    CC       src/unix/libuv_la-tcp.lo
    CC       src/unix/libuv_la-thread.lo
    CC       src/unix/libuv_la-tty.lo
    CC       src/unix/libuv_la-udp.lo
    CC       src/unix/libuv_la-linux-core.lo
    CC       src/unix/libuv_la-linux-inotify.lo
    CC       src/unix/libuv_la-linux-syscalls.lo
  src/unix/linux-core.c: In function 'read_times':
  src/unix/linux-core.c:769:21: warning: ISO C90 does not support the 'll' gnu_scanf length modifier [-Wformat=]
                       "%" PRIu64 " %" PRIu64 " %" PRIu64
                       ^~~
  src/unix/linux-core.c:769:21: warning: ISO C90 does not support the 'll' gnu_scanf length modifier [-Wformat=]
  src/unix/linux-core.c:769:21: warning: ISO C90 does not support the 'll' gnu_scanf length modifier [-Wformat=]
  src/unix/linux-core.c:769:21: warning: ISO C90 does not support the 'll' gnu_scanf length modifier [-Wformat=]
  src/unix/linux-core.c:769:21: warning: ISO C90 does not support the 'll' gnu_scanf length modifier [-Wformat=]
  src/unix/linux-core.c:769:21: warning: ISO C90 does not support the 'll' gnu_scanf length modifier [-Wformat=]
  src/unix/linux-core.c: In function 'read_cpufreq':
  src/unix/linux-core.c:806:18: warning: ISO C90 does not support the 'll' gnu_scanf length modifier [-Wformat=]
     if (fscanf(fp, "%" PRIu64, &val) != 1)
                    ^~~
  src/unix/linux-core.c: In function 'uv__read_proc_meminfo':
  src/unix/linux-core.c:972:22: warning: ISO C90 does not support the 'll' gnu_scanf length modifier [-Wformat=]
     if (1 != sscanf(p, "%" PRIu64 " kB", &rc))
                        ^~~
  src/unix/linux-core.c: In function 'uv__read_cgroups_uint64':
  src/unix/linux-core.c:1037:17: warning: ISO C90 does not support the 'll' gnu_scanf length modifier [-Wformat=]
       sscanf(buf, "%" PRIu64, &rc);
                   ^~~
    CC       src/unix/libuv_la-procfs-exepath.lo
    CC       src/unix/libuv_la-proctitle.lo
    CC       src/unix/libuv_la-sysinfo-loadavg.lo
    CCLD     libuv.la
  building 'uvloop.loop' extension
  creating build/temp.linux-mips-3.7
  creating build/temp.linux-mips-3.7/uvloop
  mipsel-openwrt-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -pipe -mno-branch-likely -mips32r2 -mtune=mips32r2 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -O2 -pipe -mno-branch-likely -mips32r2 -mtune=mips32r2 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -DNDEBUG -fno-inline -O2 -pipe -mno-branch-likely -mips32r2 -mtune=mips32r2 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -DNDEBUG -fno-inline -I/home/ryzhovau/Entware/staging_dir/target-mipsel_mips32r2_glibc-2.27/opt/include -I/home/ryzhovau/Entware/staging_dir/toolchain-mipsel_mips32r2_gcc-7.4.0_glibc-2.27/include -fPIC -I/opt/include/python3.7 -I/opt/tmp/pip-wheel-rny7k7eq/uvloop/vendor/libuv/include -c uvloop/loop.c -o build/temp.linux-mips-3.7/uvloop/loop.o -O2
  uvloop/loop.c: In function '__pyx_gb_6uvloop_4loop_4Loop_57generator3':
  uvloop/loop.c:31925:46: error: 'SO_REUSEPORT' undeclared (first use in this function)
               __pyx_t_7 = __Pyx_PyInt_From_int(SO_REUSEPORT); if (unlikely(!__pyx_t_7)) __PYX_ERR(2, 1674, __pyx_L32_error)
                                                ^~~~~~~~~~~~
  uvloop/loop.c:31925:46: note: each undeclared identifier is reported only once for each function it appears in
  error: command 'mipsel-openwrt-linux-gnu-gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for uvloop
  Running setup.py clean for uvloop
Failed to build uvloop
ERROR: Failed to build one or more wheels

**Comment by carlodri** [comment]
same problem here:

```
uvloop/loop.c: In function '__pyx_gb_6uvloop_4loop_4Loop_57generator3':
uvloop/loop.c:31925:46: error: 'SO_REUSEPORT' undeclared (first use in this function); did you mean 'SO_REUSEADDR'?
    __pyx_t_7 = __Pyx_PyInt_From_int(SO_REUSEPORT); if (unlikely(!__pyx_t_7)) __PYX_ERR(2, 1674, __pyx_L32_error)
                                     ^~~~~~~~~~~~
                                     SO_REUSEADDR
uvloop/loop.c:31925:46: note: each undeclared identifier is reported only once for each function it appears in
```

System info:

```
 Kernel Version: 4.15.0-1052-azure
 Operating System: Ubuntu 16.04.6 LTS
 OSType: linux
 Architecture: x86_64
```

**Comment by lafrinte** [comment]
same problem:

```
  gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/root/python/include/python3.7m -I/tmp/pip-install-nm7b_tln/uvloop/vendor/libuv/include -c uvloop/loop.c -o build/temp.linux-x86_64-3.7/uvloop/loop.o -O2
  uvloop/loop.c: In function ‘__pyx_gb_6uvloop_4loop_4Loop_57generator3’:
  uvloop/loop.c:31925: error: ‘SO_REUSEPORT’ undeclared (first use in this function)
  uvloop/loop.c:31925: error: (Each undeclared identifier is reported only once
  uvloop/loop.c:31925: error: for each function it appears in.)
  error: command 'gcc' failed with exit status 1
```

system:

* gcc
```
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-3) (GCC)
```

os:
```
CentOS release 6.4 (Final)
```

python: 3.7.2

**Comment by 1st1** [comment]
Hm, seems that `libuv/uv.h` no longer exposes the `SO_REUSEPORT` define.  Can you please try to add this:

```c
cdef extern from "sys/socket.h" nogil:
    cdef int SO_REUSEADDR
    cdef int SO_REUSEPORT
```

to `uvloop/includes/uv.pxd` and see if it compiles?

**Comment by Kirya2k** [comment]
I got same error with this patch of uv.pxd. :(

**Comment by 1st1** [comment]
@elprans do you have any idea what's going on here?

**Comment by 1st1** [comment]
I guess I know how to "fix" this problem -- just add a better check for `defined(SO_REUSEPORT)`, but I'm wondering why this problem didn't affect uvloop 0.12.2.

@Kirya2k few more questions:

* how do you install uvloop 0.13.0?  (via pip or manually?)
* is your system 64bit or 32bit?
* when you install uvloop 0.12.2 -- are you using the precompiled wheel package?  Can you build uvloop 0.12.2 manually?

**Comment by Kirya2k** [comment]
@1st1 

1. I tryed install uvloop via pip3.
pip3 install uvloop
Under option with patch of uv.pxd: pip3 install uvloop-0.13.0_patched.tar.gz
2. I have specific system and I suppose what at the reason in this, but @carlodri @lafrinte upper have same problem on x86.
My system have mips32 1004Kc architecture.
(This is actually a wifi router :) )

~ # lscpu
Architecture:        mips
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           4
BogoMIPS:            583.68
~ # cat /proc/cpuinfo 
system type		: MediaTek MT7621 SoC
processor		: 0
cpu model		: MIPS 1004Kc V2.15
BogoMIPS		: 583.68
wait instruction	: yes
microsecond timers	: yes
tlb_entries		: 32
extra interrupt vector	: yes
hardware watchpoint	: yes, count: 4, address/irw mask: [0x0000, 0x0000, 0x0ffb, 0x0000]
ASEs implemented	: mips16 dsp mt
shadow register sets	: 1
kscratch registers	: 0
core			: 0
VPE			: 0
VCED exceptions		: not available
VCEI exceptions		: not available

3. I build uvloop 0.12.2 manually with pip3 install.

**Comment by nehaljwani** [comment]
[socket(7)](http://man7.org/linux/man-pages/man7/socket.7.html) shows that `SO_REUSEPORT` is available since Linux Kernel 3.9.  CentOS 6.x is on ~2.6

**Comment by Kirya2k** [comment]
> [socket(7)](http://man7.org/linux/man-pages/man7/socket.7.html) shows that `SO_REUSEPORT` is >available since Linux Kernel 3.9. CentOS 6.x is on ~2.6

I have same error after upgrade kernel to 4.9
:(
And @carlodri (upper) have this error with kernel 4.15.0-1052 

~/uvloop-0.13 # uname -a
Linux Keenetic_Giga 4.9-ndm-2 #2 SMP Mon Sep 2 14:16:07 MSK 2019 mips GNU/Linux

**Comment by carlodri** [comment]
any news on this? Indeed, as @Kirya2k says, I have kernel 4.15 on Azure so kernel version should not be an issue.

**Comment by Kirya2k** [comment]
I have same error with this patch.

creating build/temp.linux-mips-3.7/uvloop
  mipsel-openwrt-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -pipe -mno-branch-likely -mips32r2 -mtune=mips32r2 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -O2 -pipe -mno-branch-likely -mips32r2 -mtune=mips32r2 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -DNDEBUG -fno-inline -O2 -pipe -mno-branch-likely -mips32r2 -mtune=mips32r2 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -DNDEBUG -fno-inline -I/home/ryzhovau/Entware/staging_dir/target-mipsel_mips32r2_glibc-2.27/opt/include -I/home/ryzhovau/Entware/staging_dir/toolchain-mipsel_mips32r2_gcc-7.4.0_glibc-2.27/include -fPIC -I/opt/include/python3.7 -I/opt/tmp/pip-req-build-7zcxqcp9/vendor/libuv/include -c uvloop/loop.c -o build/temp.linux-mips-3.7/uvloop/loop.o -O2
  uvloop/loop.c: In function '__pyx_gb_6uvloop_4loop_4Loop_57generator3':
  uvloop/loop.c:31925:46: error: 'SO_REUSEPORT' undeclared (first use in this function)
               __pyx_t_7 = __Pyx_PyInt_From_int(SO_REUSEPORT); if (unlikely(!__pyx_t_7)) __PYX_ERR(2, 1674, __pyx_L32_error)
                                                ^~~~~~~~~~~~
  uvloop/loop.c:31925:46: note: each undeclared identifier is reported only once for each function it appears in
  error: command 'mipsel-openwrt-linux-gnu-gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for uvloop
  Running setup.py clean for uvloop
Failed to build uvloop
ERROR: Failed to build one or more wheels

**Comment by 1st1** [comment]
I don't have mips and have no time to debug this. If anyone wants to submit a PR I'd really appreciate that!

**Comment by nehaljwani** [comment]
For v0.14.0, this patch works for platforms which don't support SO_REUSEPORT:
```diff
diff --git a/uvloop/loop.pyx b/uvloop/loop.pyx
index c865fed..055c01f 100644
--- a/uvloop/loop.pyx
+++ b/uvloop/loop.pyx
@@ -1712,7 +1712,7 @@ cdef class Loop:
                         if reuse_address:
                             sock.setsockopt(uv.SOL_SOCKET, uv.SO_REUSEADDR, 1)
                         if reuse_port:
-                            sock.setsockopt(uv.SOL_SOCKET, uv.SO_REUSEPORT, 1)
+                            sock.setsockopt(uv.SOL_SOCKET, SO_REUSEPORT, 1)
                         # Disable IPv4/IPv6 dual stack support (enabled by
                         # default on Linux) which makes a single socket
                         # listen on both address families.
-- 
```

**Comment by Kirya2k** [comment]
When cross-compiling, uvloop was built even without a patch. I don't have enough skills to understand what is missing with native compile. Thank you for your participation and help.
